project:
  type: website
  output-dir: docs

website:
  title: "CASA0023"
  navbar: 
    collapse: true
    search: true
    background: white
    
  sidebar:
    title: "Learning Diary"
    style: floating
    background: white
    margin-right: 5px
    margin-left: 0px
    
    contents:
      
      - href: index.qmd
        text: "Learning Content"
      #- about.qmd
      - href: 1_week.qmd
        text: "Week 1"
      - href: 2_week.qmd
        text: "Week 2"
      - href: 3_week.qmd
        text: "Week 3"
      - href: 4_week.qmd
        text: "Week 4"
      - href: 5_week.qmd
        text: "Week 5"
      
      
format:
  html:
    theme: Litera
    mainfont: serif #better to use a family type https://developer.mozilla.org/en-US/docs/Web/CSS/font-family 
    fontsize: 0.8em
    fontcolor: "#636363"  #https://htmlcolorcodes.com/ #https://colorbrewer2.org/#type=sequential&scheme=Greys&n=3 
    linkcolor: "#C1C1C1"
    monofont: serif
    css: styles.css
    toc: true
    grid: 
      body-width: 20000px
      sidebar-width: 200px
      margin-width: 200px
    #code-fold: true
    #code-tools: true
editor: visual


